version: "3.8"

volumes:
    mariadb_v:
        driver: local
        name: mariadb_v
        driver_opts:
            device: /home/aaugu/data/mariadb
            type: none
            o: bind
    wordpress_v:
        driver: local
        name: wordpress_v
        driver_opts:
            device: /home/aaugu/data/wordpress
            type: none
            o: bind

networks:
    inception:
        driver: bridge

services:
    mariadb:
        container_name: mariadb
        image: mariadb
        networks:
            - inception
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
        volumes:
            - mariadb_v:/var/lib/mysql
        restart: unless-stopped
        env_file: .env

    wordpress:
        container_name: wordpress
        image: wordpress
        volumes:
            - wordpress_v:/var/www/wordpress
        networks:
            - inception
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        depends_on:
            - mariadb
        restart: on-failure
        env_file: .env

    nginx:
        container_name: nginx
        image: nginx
        volumes:
            - wordpress_v:/var/www/wordpress
        networks:
            - inception
        depends_on:
            - wordpress
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        ports:
            - "443:443"
        restart: on-failure